FROM alpine:3.4
MAINTAINER Benjamin Borbe <bborbe@rocketnews.de>

RUN apk add --update rsync openssh bash && rm -rf /var/cache/apk/*

ENV LOCK /backup_rsync_client.lock

COPY backup_rsync_client /
ENTRYPOINT ["/backup_rsync_client"]
